name: cd-stagging

on:
  workflow_run:
    workflows: ["ci-stagging"]
    types: [completed]
    branches: [ release/* ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: stagging

    steps:
      - name: trigger deploy via hook
        env:
          RENDER_HOOK: ${{ secrets.RENDER_DEPLOYMENT_HOOK }}
        run: |
          curl -X POST "$RENDER_HOOK"
